name: shared_router
description: Router module.
version: 1.0.0
author: pahlevikun
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fluro: ^2.0.3

  foundation_injector:
    path: ../../module_foundation/foundation_injector
  foundation_identifiers:
    path: ../../module_foundation/foundation_identifiers
  shared_launcher:
    path: ../../module_shared/shared_launcher
  shared_utilities:
    path: ../../module_shared/shared_utilities
  main_product_registry:
    path: ../../main/main_product_registry

dev_dependencies:
  build_runner:
  injectable_generator:

flutter: