name: main_product_registry
description: A new Flutter project.
version: 1.0.0
author: pahlevikun
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_launcher:
    path: ../../module_shared/shared_launcher
  product_splash:
    path: ../../module_product/product_splash
  product_authentication:
    path: ../../module_product/product_authentication

flutter: