name: assets
description: assets generator.
version: 1.0.0
author: pahlevikun
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.1.1
  dart_style: ^2.0.1
  path: ^1.8.0
  yaml: ^3.1.0
  recase: ^4.0.0
  build: ^2.0.3
  build_config: ^1.0.0

dev_dependencies:
  lint: ^1.5.3
